### ISSUE TITLE
Build x86_64 image

### ISSUE THREAD

**Issue by meyskens** [scaleway-community/scaleway-ubuntu-coreos#8]
Build an x86_64 for the C2. Also set the model tag to be the one fetched from the metadata for unit files to run on specific architectures.

**Comment by meyskens** [comment]
@moul are there any build instructions for the C2?

**Comment by moul** [comment]
@meyskens it is still experimental, but take a look at my commits on any images I recently added the multiarch support

**Comment by meyskens** [comment]
Will do :+1:  Currently playing with the multiarch docker images first.
