### ISSUE TITLE
Fix build in qemu

### ISSUE THREAD

**Issue by meyskens** [scaleway-community/scaleway-ubuntu-coreos#9]
The golang install fails in qemu, this is related to https://bugs.launchpad.net/ubuntu/+source/golang/+bug/1501651

**Comment by moul** [comment]
Yes, sometimes it just won't work in QEMU, so I fallback on a native builder on a C1

**Comment by meyskens** [comment]
Will be fixed in xenial for what I can read. Doing the same for the C1 for now.
